### ISSUE TITLE
autosync fails

### ISSUE THREAD

**Issue by dentex** [Gro2mi/gyroflow#9]
Hi, I tried your fork, as suggested over Discord (muon_FPV); I switched to branch `auto_sync_point_suggestion`, but as soon as I hit the button `[Attempt Auto Sync]`, I get this:

```
25.0 degree gyro/camera angle
Preset name: GoPro_Hero 8 Black__2.7K_4:3_60fps_wide
Note: No ND Filter or Hypersmooth
Made with 35 frames using calibrator version 0.2.1-alpha on date 2021-04-30
Note: Versions don't match. Calibrator: 0.3.0-beta, Preset: 0.2.1-alpha. Should be fine though.
/home/[...]/GX010114.mp4
[warn] [/atom[2]/movie/atom[3]/track/atom[3]/media/atom[1]/hdlr] [Autofix] Delete '/atom[2]/movie/atom[3]/track/atom[3]/media/atom[1]/hdlr/name' (too large)
[warn] [/atom[2]/movie/atom[3]/track/atom[3]/media/atom[1]/hdlr] [Autofix] Fix parser error: stop parser, add padding
[warn] [/atom[2]/movie/atom[4]/track/atom[2]/media/atom[1]/hdlr] [Autofix] Delete '/atom[2]/movie/atom[4]/track/atom[2]/media/atom[1]/hdlr/name' (too large)
[warn] [/atom[2]/movie/atom[4]/track/atom[2]/media/atom[1]/hdlr] [Autofix] Fix parser error: stop parser, add padding
[warn] [/atom[2]/movie/atom[4]/track/atom[2]/media/atom[2]/minf/atom[2]/stbl/atom[0]/stsd/sample_entry[0]/atom[0]/esds/ES/decConfigDescr/reserved] padding contents doesn't look normal (invalid pattern)
[warn] [/atom[2]/movie/atom[5]/track/atom[1]/media/atom[1]/hdlr] [Autofix] Delete '/atom[2]/movie/atom[5]/track/atom[1]/media/atom[1]/hdlr/name' (too large)
[warn] [/atom[2]/movie/atom[5]/track/atom[1]/media/atom[1]/hdlr] [Autofix] Fix parser error: stop parser, add padding
Accl rate: 203.00186308715766 Hz, should be close to 200 or 400 Hz
GoPro GPMF metadata
GoPro GPMF metadata
average_frame_duration: 0.004926063164113208
missing_runs: []
Appending 0.0..=211.23944060350257
average_frame_duration: 0.004926063164113208
missing_runs: []
Appending 0.0..=211.23944060350257
Gyro rate: 203.00659705159697
Trim start:  3.164405529207516
Trim end:  203.95590980549352
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/range.py", line 376, in get_loc
    return self._range.index(new_key)
ValueError: 43239 is not in range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gyroflow.py", line 2556, in auto_sync_start
    success = self.stab.full_auto_sync(max_fitting_error, max_syncs)
  File "/home/samuele/GIT/gyroflow_Gro2mi/stabilizer.py", line 690, in full_auto_sync
    syncpoints = self.get_recommended_syncpoints(num_frames_analyze, max_points=max_points, debug_plots=debug_plots)
  File "/home/samuele/GIT/gyroflow_Gro2mi/stabilizer.py", line 635, in get_recommended_syncpoints
    self.gyro_analysis(analyzed_time, debug_plots=debug_plots)
  File "/home/samuele/GIT/gyroflow_Gro2mi/stabilizer.py", line 599, in gyro_analysis
    recommended_syncs = recommended_syncs.append({'t': df.loc[ii + best].t_roll, 'rating': df.loc[ii + best].rating}, ignore_index=True)
  File "/usr/lib/python3/dist-packages/pandas/core/indexing.py", line 1424, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/lib/python3/dist-packages/pandas/core/indexing.py", line 1850, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/usr/lib/python3/dist-packages/pandas/core/indexing.py", line 160, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/usr/lib/python3/dist-packages/pandas/core/generic.py", line 3737, in xs
    loc = self.index.get_loc(key)
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/range.py", line 378, in get_loc
    raise KeyError(key)
KeyError: 43239
```

I hope this helps, bye.

**Comment by Gro2mi** [comment]
Fixed.
